default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", "postgres") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
  username: <%= ENV.fetch("POSTGRES_USER", "rails") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "rails") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB_TEST", "app_test") %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DB", "app_production") %>
  url: <%= ENV["DATABASE_URL"] %>
